/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AudioManager")]
    [LuaRegisterType(0x54ef1694c40a5ef8, typeof(LuaBehaviour))]
    public class AudioManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6ebc180f80f30cd4392c84bdb1e6ca6b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_bgmRare = default;
        [SerializeField] public Highrise.AudioShader m_bgmEpic = default;
        [SerializeField] public Highrise.AudioShader m_bgmLegendary = default;
        [SerializeField] public Highrise.AudioShader m_sfxButtonClick = default;
        [SerializeField] public Highrise.AudioShader m_sfxSendIngredient = default;
        [SerializeField] public Highrise.AudioShader m_sfxSubmitOrder = default;
        [SerializeField] public System.Double m_musicVolume = 0.5;
        [SerializeField] public System.Double m_sfxVolume = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_bgmRare),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_bgmEpic),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_bgmLegendary),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_sfxButtonClick),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_sfxSendIngredient),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_sfxSubmitOrder),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_musicVolume),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_sfxVolume),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/AudioManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
