/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GeneralChat")]
    [LuaRegisterType(0x7f9a01ee37e562d5, typeof(LuaBehaviour))]
    public class GeneralChat : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9f704bff1826b43a3834478cd1499710";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Enable to customize the chat bubble colors")]
        [SerializeField] public System.Boolean m_customChatBubbleColors = false;
        [Tooltip("Chat bubble background color used for other players")]
        [SerializeField] public UnityEngine.Color m_defaultChatBubbleBackgroundColor = new Color(1f, 1f, 1f, 1f);
        [Tooltip("Chat bubble font color used for other players")]
        [SerializeField] public UnityEngine.Color m_defaultChatBubbleFontColor = new Color(0f, 0f, 0f, 1f);
        [Tooltip("Chat bubble background color used for messages you send")]
        [SerializeField] public UnityEngine.Color m_selfChatBubbleBackgroundColor = new Color(0.157f, 0.153f, 0.176f, 1f);
        [Tooltip("Chat bubble font color used for messages you send")]
        [SerializeField] public UnityEngine.Color m_selfChatBubbleFontColor = new Color(0.521f, 0.38f, 1f, 1f);
        [Tooltip("Enable to customize the chat bubble sounds")]
        [SerializeField] public System.Boolean m_customChatBubbleSound = false;
        [Tooltip("Sound to play when a chat message is sent, if left empty then no sound will play")]
        [SerializeField] public Highrise.AudioShader m_chatSentSound = default;
        [Tooltip("Sound to play when a chat bubble appears, if left empty then no sound will play")]
        [SerializeField] public Highrise.AudioShader m_chatBubbleSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_customChatBubbleColors),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_defaultChatBubbleBackgroundColor),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_defaultChatBubbleFontColor),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_selfChatBubbleBackgroundColor),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_selfChatBubbleFontColor),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_customChatBubbleSound),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_chatSentSound),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_chatBubbleSound),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/GeneralChat/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
