/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/IngredientTapped")]
    [LuaRegisterType(0x271accaafa688d2c, typeof(LuaBehaviour))]
    public class IngredientTapped : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f33ca11ede8afe14e806d40b0e93c293";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("f1b2f20e42443e04a9ed989be1a0beac")]
        [SerializeField] public UnityEngine.Object m_IngredientData = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_IngredientData),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/IngredientTapped/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
