/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/IngredientsBase")]
    [LuaRegisterType(0x8a97beaf6a9c67aa, typeof(LuaScriptableObject))]
    public class IngredientsBase : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "f1b2f20e42443e04a9ed989be1a0beac";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_name = "";
        [SerializeField] public UnityEngine.Sprite m_icon = default;
        [SerializeField] public UnityEngine.GameObject m_prefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_name),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_icon),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_prefab),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/IngredientsBase/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
