/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/InWorldHUD")]
    [LuaRegisterType(0x908d878efd707fdf, typeof(LuaBehaviour))]
    public class InWorldHUD : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e2685c45b5ed455488c51db28d6529b0";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture2D m_spriteIcon = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_spriteIcon),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/InWorldHUD/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
