/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/LoadingScreen")]
    [LuaRegisterType(0x2df0080d61a6dbb, typeof(LuaBehaviour))]
    public class LoadingScreen : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5700a6d5a8892524f89cbe6c535d817a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture2D m_loadingImage = default;
        [SerializeField] public System.Double m_delayBeforeFade = 2;
        [SerializeField] public System.Double m_fadeDuration = 1.5;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_loadingImage),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_delayBeforeFade),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_fadeDuration),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/LoadingScreen/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
