/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/OrdersManager")]
    [LuaRegisterType(0x7ae6f5e6f22b6ab3, typeof(LuaBehaviour))]
    public class OrdersManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8e68ebe2280d0b04b92bb75cea3ac7c8";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("99f1d7bb5d7925542ba381d0a7322a4f")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_OrdersList = default;
        [LuaScriptPropertyAttribute("553105638870fa04d8f87070d9067d8a")]
        [SerializeField] public UnityEngine.Object m_GameHUD = default;
        [SerializeField] public UnityEngine.GameObject m_CounterObject = default;
        [SerializeField] public UnityEngine.GameObject m_OrderCompleteVFX = default;
        [SerializeField] public UnityEngine.GameObject m_indicatorObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_OrdersList),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_GameHUD),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_CounterObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_OrderCompleteVFX),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_indicatorObject),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/OrdersManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
