/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/OrdersBase")]
    [LuaRegisterType(0x311e23f602be4cd9, typeof(LuaScriptableObject))]
    public class OrdersBase : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "99f1d7bb5d7925542ba381d0a7322a4f";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_name = "";
        [LuaScriptPropertyAttribute("f1b2f20e42443e04a9ed989be1a0beac")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_ingredients = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_name),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_ingredients),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/OrdersBase/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
