/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RoomManager")]
    [LuaRegisterType(0x7dd97b47ed53e961, typeof(LuaBehaviour))]
    public class RoomManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "94e992bc9fec01747a5326fe6d8c49ad";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("878647f2b93d26646ac24796f4ae0cdc")]
        [SerializeField] public UnityEngine.Object m_RoomMeterHUD = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_RoomMeterHUD),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RoomManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
