/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/SnugglinBase")]
    [LuaRegisterType(0x8af4012c0dd40439, typeof(LuaScriptableObject))]
    public class SnugglinBase : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "b524554a0243acf4fb4bc7a2d97c12b7";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_name = "";
        [SerializeField] public Highrise.CharacterOutfit m_outfit = default;
        [SerializeField] public System.String m_rarity = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_name),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_outfit),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_rarity),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/SnugglinBase/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
