/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SnugglinManager")]
    [LuaRegisterType(0xcae14f7717f70993, typeof(LuaBehaviour))]
    public class SnugglinManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "743f861636b7f4d4ba171fcd245afc01";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_snugglinPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_spawnPointOBJ = default;
        [SerializeField] public System.Collections.Generic.List<Highrise.Client.Anchor> m_sittingAnchors = default;
        [LuaScriptPropertyAttribute("b524554a0243acf4fb4bc7a2d97c12b7")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_snugglinData = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_snugglinPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_spawnPointOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_sittingAnchors),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_snugglinData),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/SnugglinManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
